set autoindent
set backupdir=$HOME/vimbackup
set browsedir=buffer
set clipboard=unnamed
set directory=$HOME/vimbackup
set expandtab
set list
set shiftwidth=2
set showmatch
set ignorecase
set smartcase
set smartindent
set smarttab
set tabstop=2
set whichwrap=b,s,h,l,<,>,[,]
set backspace=eol,start,indent
set laststatus=2
set statusline=%F%M%R%=code:%B%H%W
